### ISSUE TITLE
Tratamento erro para classId em POST LessonPlan

### ISSUE THREAD

**Issue by diCaminha** [gladguys/aluco-api#80]
se o classId n é passado, vai dar esse erro: 

postgresql.util.PSQLException: ERROR: insert or update on table "lesson_plan" violates foreign key constraint "fkfnd8rebhfi9wo9obc6lfmyh11"
  Detail: Key (class_id)=(5) is not present in table "class".
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440) ~[postgresql-42.2.5.jar:42.2.5]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183) ~[postgresql-42.2.5.jar:42.2.5]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308) ~[postgresql-42.2.5.jar:42.2.5]
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441) ~[postgresql-42.2.5.jar:42.2.5]
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365) ~[postgresql-42.2.5.jar:42.2.5]
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143) ~[postgresql-42.2.5.jar:42.2.5]

**Comment by lailsonbento** [comment]
Acho que é porque não está retornando no getById e getAll, por exemplo
